from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from graph import graph
from langchain_core.messages import HumanMessage


app = FastAPI(
    title="Acme Time-Off API",
    version="1.0.0",
)


# --------------------------------------------------
# CORS
# --------------------------------------------------

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --------------------------------------------------
# Request / Response Models
# --------------------------------------------------

class ChatRequest(BaseModel):
    message: str


class ChatResponse(BaseModel):
    response: str


# --------------------------------------------------
# Conversation State
# --------------------------------------------------

# For now, keep one conversation in memory.
# Later we can replace this with session IDs / database / Redis.

conversation_state = {
    "messages": [],
    "employee_id": "EMP002",

    # These are included because your PTOState contains them.
    "employee": {},
    "tool_results": {},
    "retrieved_docs": [],
    "final_response": "",
    "needs_clarification": False,
    "clarification_question": "",
    "summary": "",
    "intent": "",
    "can_proceed": False,
}


# --------------------------------------------------
# Health Check
# --------------------------------------------------

@app.get("/")
def root():
    return {
        "message": "Acme Time-Off API is running"
    }


@app.get("/health")
def health():
    return {
        "status": "ok"
    }


# --------------------------------------------------
# Chat Endpoint
# --------------------------------------------------

@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):

    user_message = request.message.strip()

    if not user_message:
        return {
            "response": "Please enter a message."
        }

    # Add current user message
    conversation_state["messages"].append(
        HumanMessage(content=user_message)
    )

    try:
        # Run existing LangGraph
        result = graph.invoke(conversation_state)

        # Update stored state
        conversation_state.update(result)

        # Last message generated by the graph
        messages = result.get("messages", [])

        if not messages:
            return {
                "response": "I couldn't generate a response."
            }

        last_message = messages[-1]

        response_content = last_message.content

        # Claude/LangChain content can occasionally be structured
        # rather than a plain string.
        if isinstance(response_content, str):
            final_response = response_content

        elif isinstance(response_content, list):
            text_parts = []

            for block in response_content:
                if isinstance(block, dict):
                    if block.get("type") == "text":
                        text_parts.append(
                            block.get("text", "")
                        )

            final_response = "\n".join(text_parts).strip()

        else:
            final_response = str(response_content)

        return {
            "response": final_response
        }

    except Exception as e:
        print("\n========== API ERROR ==========")
        print(type(e).__name__, ":", e)
        print("===============================\n")

        return {
            "response": (
                "Sorry, something went wrong while processing "
                "your request."
            )
        }